In [4]:
import numpy as np

# Datatypes and Attributes

In [5]:
# Numpy's main data type is ndarray(N-Dimensional Array)
a1 = np.array([2,5,6,1,9,8])
a1

array([2, 5, 6, 1, 9, 8])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
#Attribbute
a1.shape

(6,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape
#The First will be along axios[0](Depth) second on axis[1] and so on

(2, 3, 3)

In [13]:
# TO know about the dimensions use ndim
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [14]:
# To know about the datatype use dtype
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
#To know about the size 
a1.size , a2.size , a3.size

(6, 6, 18)

In [16]:
# To know about the type
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
#Create a Dataframe from Numpy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
#TO create a array/Matrix with all ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones = np.ones((2,3),int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
zeros = np.zeros((2,2),int)
zeros

array([[0, 0],
       [0, 0]])

In [22]:
# To create a array from 1 to n number 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
# To create a array with random numbers
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[9, 2, 3, 5, 3],
       [8, 8, 8, 3, 7],
       [3, 1, 2, 1, 9]], dtype=int32)

In [24]:
#Another Way to creater a random array
np.random.random((3,5))

array([[0.61796534, 0.43470451, 0.85682212, 0.23350993, 0.16761191],
       [0.14812097, 0.27382467, 0.79791668, 0.47022529, 0.79715402],
       [0.49229722, 0.02226146, 0.09479303, 0.09403674, 0.12043233]])

In [25]:
np.random.rand(3,5)

array([[0.91165158, 0.00365469, 0.47856203, 0.20209955, 0.03095157],
       [0.9474011 , 0.90120697, 0.03862025, 0.80422552, 0.75037953],
       [0.8345545 , 0.79229487, 0.70651058, 0.72553388, 0.3764845 ]])

In [26]:
#Pseudo random Number
np.random.seed(seed=0)
random_array2 = np.random.randint(10,size=(5,3))
random_array2
#This will genrate the random Numbers but when rerun will not genrate new random Number

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

## 3. Viewing Array and Matrices

In [27]:
# To find the unique Elements in the Array
random_array

array([[9, 2, 3, 5, 3],
       [8, 8, 8, 3, 7],
       [3, 1, 2, 1, 9]], dtype=int32)

In [28]:
np.unique(random_array)

array([1, 2, 3, 5, 7, 8, 9], dtype=int32)

In [29]:
a1

array([2, 5, 6, 1, 9, 8])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1[0],a1[1],a1[2]

(np.int64(2), np.int64(5), np.int64(6))

In [33]:
a2[0]

array([1. , 2. , 3.3])

In [34]:
a2[1][2]

np.float64(6.5)

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[0][1]

array([4, 5, 6])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]], dtype=int32)

In [39]:
a4[0]

array([[[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]],

       [[8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]]], dtype=int32)

In [40]:
a4[0][0]

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3]], dtype=int32)

In [41]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [42]:
#Get the first four number of the innermost Array
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]], dtype=int32)

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [43]:
a1 

array([2, 5, 6, 1, 9, 8])

In [48]:
ones = np.ones(6)
ones

array([1., 1., 1., 1., 1., 1.])

In [49]:
a1 + ones

array([ 3.,  6.,  7.,  2., 10.,  9.])

In [50]:
a1 * ones

array([2., 5., 6., 1., 9., 8.])

In [58]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [63]:
# How to reshape a2 to combine with a3 ?
# Search : "How to Reshape a Array in Numpy"

In [64]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [65]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [66]:
# Square
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [67]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [69]:
a1 = np.array([1,2,3,4,5,6])
np.add(a1,ones)

array([2., 3., 4., 5., 6., 7.])

In [70]:
a1%2

array([1, 0, 1, 0, 1, 0])

In [71]:
np.exp(a1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [72]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])