In [1]:
import numpy as np

# Datatypes and Attributes

In [2]:
# Numpy's main data type is ndarray(N-Dimensional Array)
a1 = np.array([2,5,6,1,9,8])
a1

array([2, 5, 6, 1, 9, 8])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
#Attribbute
a1.shape

(6,)

In [9]:
a2.shape

(2, 3)

In [11]:
a3.shape
#The First will be along axios[0](Depth) second on axis[1] and so on

(2, 3, 3)

In [12]:
# TO know about the dimensions use ndim
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [13]:
# To know about the datatype use dtype
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
#To know about the size 
a1.size , a2.size , a3.size

(6, 6, 18)

In [18]:
# To know about the type
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
#Create a Dataframe from Numpy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
#TO create a array/Matrix with all ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones = np.ones((2,3),int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
zeros = np.zeros((2,2),int)
zeros

array([[0, 0],
       [0, 0]])

In [31]:
# To create a array from 1 to n number 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
# To create a array with random numbers
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[6, 7, 0, 6, 0],
       [2, 5, 4, 4, 0],
       [1, 8, 8, 9, 9]], dtype=int32)

In [33]:
#Another Way to creater a random array
np.random.random((3,5))

array([[0.06427994, 0.94738609, 0.80071104, 0.76840343, 0.60559314],
       [0.63486661, 0.8406941 , 0.19361013, 0.66565564, 0.38463503],
       [0.05560608, 0.2055931 , 0.48057927, 0.53087108, 0.02173101]])

In [34]:
np.random.rand(3,5)

array([[0.04004254, 0.94509172, 0.35061512, 0.3216428 , 0.89034108],
       [0.07751217, 0.4557304 , 0.15413111, 0.24076002, 0.64975849],
       [0.16085421, 0.80837823, 0.01611728, 0.85320347, 0.02419479]])