In [1]:
import numpy as np

# Datatypes and Attributes

In [2]:
# Numpy's main data type is ndarray(N-Dimensional Array)
a1 = np.array([2,5,6,1,9,8])
a1

array([2, 5, 6, 1, 9, 8])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
#Attribbute
a1.shape

(6,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape
#The First will be along axios[0](Depth) second on axis[1] and so on

(2, 3, 3)

In [10]:
# TO know about the dimensions use ndim
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [11]:
# To know about the datatype use dtype
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
#To know about the size 
a1.size , a2.size , a3.size

(6, 6, 18)

In [13]:
# To know about the type
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
#Create a Dataframe from Numpy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
#TO create a array/Matrix with all ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones = np.ones((2,3),int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
zeros = np.zeros((2,2),int)
zeros

array([[0, 0],
       [0, 0]])

In [19]:
# To create a array from 1 to n number 
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# To create a array with random numbers
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 3, 1, 5, 0],
       [4, 6, 1, 6, 9],
       [3, 3, 6, 8, 0]], dtype=int32)

In [21]:
#Another Way to creater a random array
np.random.random((3,5))

array([[0.50773712, 0.97631054, 0.83268763, 0.37477701, 0.67193265],
       [0.37068204, 0.14501898, 0.51468595, 0.0578467 , 0.03192067],
       [0.25111801, 0.59483964, 0.37325928, 0.19109725, 0.55830643]])

In [22]:
np.random.rand(3,5)

array([[0.64844997, 0.29762547, 0.20740404, 0.64481636, 0.07278856],
       [0.12086182, 0.90705751, 0.3561641 , 0.095596  , 0.82929263],
       [0.21900713, 0.4243369 , 0.49970896, 0.36219093, 0.15506968]])

In [23]:
#Pseudo random Number
np.random.seed(seed=0)
random_array2 = np.random.randint(10,size=(5,3))
random_array2
#This will genrate the random Numbers but when rerun will not genrate new random Number

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

## 3. Viewing Array and Matrices

In [24]:
# To find the unique Elements in the Array
random_array

array([[8, 3, 1, 5, 0],
       [4, 6, 1, 6, 9],
       [3, 3, 6, 8, 0]], dtype=int32)

In [25]:
np.unique(random_array)

array([0, 1, 3, 4, 5, 6, 8, 9], dtype=int32)

In [26]:
a1

array([2, 5, 6, 1, 9, 8])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1[0],a1[1],a1[2]

(np.int64(2), np.int64(5), np.int64(6))

In [36]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a2[1][2]

np.float64(6.5)

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a3[0][1]

array([4, 5, 6])

In [42]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [43]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]], dtype=int32)

In [44]:
a4[0]

array([[[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]],

       [[8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]]], dtype=int32)

In [45]:
a4[0][0]

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3]], dtype=int32)

In [46]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [47]:
#Get the first four number of the innermost Array
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]], dtype=int32)